@startuml
[*] -> Begin : CS asserted low
Begin -> LoadAddress : SCLK Posedge
LoadAddress -> LoadAddress : Read 7 bits
LoadAddress --> HandleReadWrite : SCLK Posedge
HandleReadWrite -> Wait : RW bit received
Wait --> StartRead : Read?
StartRead -> EndRead : SCLK Posedge
Wait -> Write : Write?
Write -> Write : Write 8 bits
EndRead --> Begin : SCLK Posedge
EndRead -> EndRead : Read 8 bits
Write --> Begin : SCLK Posedge
@enduml
